debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

server:
  port: 1002

spring:
  webflux:
    base-path: /api

#actuator / management
management:
  endpoints:
    web:
      exposure:
        include: "*"
